URI=v1/configs/system
BASENAME=system_config
CLASSNAME=SysetmConfig
METHODLIST=list,create,update,retrieve,detail_create,detail_update

URI=v1/configs/interfaces
BASENAME=interface_config
CLASSNAME=InterfaceConfig
METHODLIST=list,create,update,retrieve,detail_create,detail_update

URI=v1/configs/vlans
BASENAME=vlan_config
CLASSNAME=VlanConfig
METHODLIST=list,create,update,retrieve,detail_create,detail_update

URI=v1/statistics
BASENAME=if_statistics
CLASSNAME=IfStatistics
METHODLIST=list,retrieve
