# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPortTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(max_length=30)),
                ('ifindex', models.IntegerField()),
                ('txBytes', models.IntegerField()),
                ('rxBytes', models.IntegerField()),
                ('txPkts', models.IntegerField()),
                ('rxPkts', models.IntegerField()),
            ],
        ),
    ]
