'''
This file was automatically generated by rmib_compiler.py.
DO NOT EDIT.
'''


from puci.interface import *
from puci.system import *

'''
 Define SAL Method
'''
SAL_METHOD_LIST           = 1
SAL_METHOD_RETRIEVE       = 2
SAL_METHOD_CREATE         = 3
SAL_METHOD_UPDATE         = 4
SAL_METHOD_PARTIAL_UPDATE = 5
SAL_METHOD_DELETE         = 6




'''
 Define system_config SAL function
'''
def sal_system_config(method, request, pk):
  if method == SAL_METHOD_LIST:
    return system_config_list()
  if method == SAL_METHOD_CREATE:
    return system_config_create(request)
  if method == SAL_METHOD_UPDATE:
    return system_config_update(request)
  if method == SAL_METHOD_RETRIEVE:
    return system_config_retrieve(pk, 1)
  if method == SAL_METHOD_DETAIL_CREATE:
    return system_config_detail_create(request, pk)
  if method == SAL_METHOD_DETAIL_UPDATE:
    return system_config_detail_update(request, pk)
  return None


'''
 Define interface_config SAL function
'''
def sal_interface_config(method, request, pk):
  if method == SAL_METHOD_LIST:
    return interface_config_list()
  if method == SAL_METHOD_CREATE:
    return interface_config_create(request)
  if method == SAL_METHOD_UPDATE:
    return interface_config_update(request)
  if method == SAL_METHOD_RETRIEVE:
    return interface_config_retrieve(pk, 1)
  if method == SAL_METHOD_DETAIL_CREATE:
    return interface_config_detail_create(request, pk)
  if method == SAL_METHOD_DETAIL_UPDATE:
    return interface_config_detail_update(request, pk)
  return None


'''
 Define vlan_config SAL function
'''
def sal_vlan_config(method, request, pk):
  if method == SAL_METHOD_LIST:
    return vlan_config_list()
  if method == SAL_METHOD_CREATE:
    return vlan_config_create(request)
  if method == SAL_METHOD_UPDATE:
    return vlan_config_update(request)
  if method == SAL_METHOD_RETRIEVE:
    return vlan_config_retrieve(pk, 1)
  if method == SAL_METHOD_DETAIL_CREATE:
    return vlan_config_detail_create(request, pk)
  if method == SAL_METHOD_DETAIL_UPDATE:
    return vlan_config_detail_update(request, pk)
  return None


'''
 Define if_statistics SAL function
'''
def sal_if_statistics(method, request, pk):
  if method == SAL_METHOD_LIST:
    return if_statistics_list()
  if method == SAL_METHOD_RETRIEVE:
    return if_statistics_retrieve(pk, 1)
  return None
