'''
This file was automatically generated by rmib_compiler.py.
 DO NOT EDIT.
'''


from apServer.server import views
from apServer.server.custom_classes import CustomRouter

custom_router = CustomRouter()

custom_router.register(r'v1/infos/usages', views.SysetmUsageViewSet, base_name='system_usage')
custom_router.register(r'v1/infos/systems/device-reg-info', views.SystemInfoViewSet, base_name='system_info')
custom_router.register(r'v1/infos/systems/times', views.SystemTimeInfoViewSet, base_name='system_time_info')
custom_router.register(r'v1/infos/systems/interfaces', views.InterfaceInfoViewSet, base_name='interface_info')
custom_router.register(r'v1/infos/systems/interface-addresses', views.InterfaceAddressInfoViewSet, base_name='interface_address_info')
custom_router.register(r'v1/infos/systems/wireless', views.WirelessInfoViewSet, base_name='wireless_info')
custom_router.register(r'v1/infos/wireless/wireless-stations', views.WirelessStationViewSet, base_name='wireless_station')
custom_router.register(r'v1/infos/wireless/wireless-search', views.WirelessSearchViewSet, base_name='wireless_search')
custom_router.register(r'v1/infos/dhcp/dhcp-leases', views.DhcpLeasesViewSet, base_name='dhcp_leases')
custom_router.register(r'v1/configs/provisioning-done', views.ProvisioningDoneViewSet, base_name='provisioning_done')
custom_router.register(r'v1/keepalive-check', views.KeepaliveCheckViewSet, base_name='keepalive_check')
custom_router.register(r'v1/configs/system', views.SysetmConfigViewSet, base_name='system_config')
custom_router.register(r'v1/configs/interfaces', views.InterfaceConfigViewSet, base_name='interface_config')
custom_router.register(r'v1/configs/vlans', views.VlanConfigViewSet, base_name='vlan_config')
custom_router.register(r'v1/configs/dhcp/common', views.DhcpCommonConfigViewSet, base_name='dhcp_common_config')
custom_router.register(r'v1/configs/dhcp/pools', views.DhcpPoolConfigViewSet, base_name='dhcp_pool_config')
custom_router.register(r'v1/configs/dhcp/static-leases', views.DhcpStaticLeasesConfigViewSet, base_name='dhcp_static_leases_config')
custom_router.register(r'v1/configs/snmp', views.SNMPConfigViewSet, base_name='snmp_config')
custom_router.register(r'v1/configs/wireless', views.WirelessConfigViewSet, base_name='wireless_config')
custom_router.register(r'v1/configs/firewall/port-forwarding', views.PortForwardingViewSet, base_name='port_forwarding')
custom_router.register(r'v1/management/firmware', views.FirmwareMgtViewSet, base_name='firmware_management')
custom_router.register(r'v1/management/system-reboot', views.SystemRebootViewSet, base_name='system_reboot')
custom_router.register(r'v1/statistics', views.IfStatisticsViewSet, base_name='if_statistics')
custom_router.register(r'v1/virtualization/images', views.DockerImagesViewSet, base_name='docker_images')
custom_router.register(r'v1/virtualization/containers-creation', views.ContainerCreationViewSet, base_name='container_creation')
custom_router.register(r'v1/virtualization/containers', views.ContainerGetViewSet, base_name='container_get')
custom_router.register(r'v1/virtualization/containers-management', views.ContainerManagementViewSet, base_name='container_management')
