'''
This file was automatically generated by rmib_compiler.py.
DO NOT EDIT.
'''


from apServer.server import views
from common.generic_defs import CustomRouter

custom_router = CustomRouter()

custom_router.register(r'v1/configs/system', views.SysetmConfigViewSet, base_name='system_config')
custom_router.register(r'v1/configs/interfaces', views.InterfaceConfigViewSet, base_name='interface_config')
custom_router.register(r'v1/configs/vlans', views.VlanConfigViewSet, base_name='vlan_config')
custom_router.register(r'v1/statistics', views.IfStatisticsViewSet, base_name='if_statistics')
