'''
This file was automatically generated by rmib_compiler.py.
DO NOT EDIT.
'''


from common.log import *

CONFIG_TYPE_SCALAR=1
CONFIG_TYPE_LIST=2


def uci_get_section_map(config_name, *args):

  log_info(LOG_MODULE_SAL, "ARGS: " + str(args))

  if config_name == 'systemConfigLogging':
    section_map = {
      'loggingBufferSize'      :  [ CONFIG_TYPE_SCALAR  , 'system.@system[0].log_size'                 ,' ' ],
      'loggingServerIpAddr'    :  [ CONFIG_TYPE_SCALAR  , 'system.@system[0].log_ip'                   ,' ' ],
      'loggingServerPort'      :  [ CONFIG_TYPE_SCALAR  , 'system.@system[0].log_ip'                   ,' ' ],
      'loggingServerProtocol'  :  [ CONFIG_TYPE_SCALAR  , 'system.@system[0].log_proto'                ,' ' ],
      'loggingFilename'        :  [ CONFIG_TYPE_SCALAR  , 'system.@system[0].log_file'                 ,' ' ],
      'loggingOutputLevel'     :  [ CONFIG_TYPE_SCALAR  , ''                                           ,' ' ],
      'loggingCronLogLevel'    :  [ CONFIG_TYPE_SCALAR  , ''                                           ,' ' ],
    }
    return section_map

  if config_name == 'interfaceConfig':
    section_map = {
      'ifname'                 :  [ CONFIG_TYPE_SCALAR  , ".".join([config_name, args[0], 'ifname'])   ,' ' ],
      'protocol'               :  [ CONFIG_TYPE_SCALAR  , ".".join([config_name, args[0], 'proto'])    ,' ' ],
      'type'                   :  [ CONFIG_TYPE_SCALAR  , ".".join([config_name, args[0], 'type'])     ,' ' ],
    }
    return section_map

