#!/bin/sh /etc/rc.common

START=80

GUNICORN=/usr/bin/gunicorn
APSERVER_DIR=/www/openAPgent

start() {
	cd $APSERVER_DIR
	$GUNICORN --workers 1 --error-logfile /var/log/gunicorn.log --daemon --reload    \
            --bind unix:/www/openAPgent/apServer.sock apServer.wsgi:application
	echo "run gunicorn..."
}

stop() {
	echo "stop gunicorn..."
	killall gunicorn
}
