#!/bin/sh /etc/rc.common

# This script is startup-config using uci.
# The following commands overwrite default uci config.

START=99


stop() {
	echo "do noting..."
}

start() {
	#
	# Network Configuration
	#
	uci set network.lan.ipaddr='172.33.1.1'
	uci set network.lan.netmask='255.255.0.0'

	uci set network.lan.igmp_snooping='1'
	uci commit network
	ifdown lan;ifup lan
}
