#!/bin/sh /etc/rc.common

# This script is startup-config using uci.
# The following commands overwrite default uci config.

START=99


stop() {
	echo "do noting..."
}

start() {
	uci set firewall.@zone[1].input='ACCEPT'
	uci set firewall.@zone[1].forward='ACCEPT'

	uci set network.lan.igmp_snooping='1'
}
