#!/bin/sh /etc/rc.common

# This script is startup-config using uci.
# The following commands overwrite default uci config.

START=99


stop() {
	echo "do noting..."
}

start() {
	uci set firewall.@zone[1].input='ACCEPT'
	uci set firewall.@zone[1].forward='ACCEPT'

	uci commit firewall
	/etc/init.d/firewall restart

	uci set network.lan.igmp_snooping='1'

	uci delete network.lan.ipaddr
	uci delete network.lan.netmask

#	uci set network.wan.ipaddr='192.168.74.2'
#	uci set network.wan.netmask='255.255.0.0'
	uci set network.wan.proto='dhcp'
#	uci set network.wan.gateway='192.168.255.254'
	uci set network.wan.dns='8.8.8.8'

	uci commit network
	/etc/init.d/network restart
}
